---
# Test Runner defaulta documentation
# 
# copy this file to cwd with the name 'suite_runner_configs.yaml' and
# add following lines to Rakefile
#
#  suite_runner_configs= "suite_runner_configs.yaml"
#  $suite_runner_configs = File.exist?(suite_runner_configs) ? YAML.load_file( suite_runner_configs ) : {}
#
#  spec = Gem::Specification.find_by_name 'aws-must-templates'
#  load "#{spec.gem_dir}/lib/tasks/suite.rake"
#
# 

# SSH Client Configuration file where EC2 Instance Tag Name/DNS Name
# mapping is written
ssh_config_file: ssh/config.aws

# Name of file, which is used to seed 'ssh_config_file', if
# it does not exist
ssh_config_init: ssh/config.init

# AWS region for AWS SDK
# aws_region: 
aws_region: eu-west-1
