description: Example configuration for VPC


parameters:

        -  Name: &Param_InstanceTypeName InstanceType
           Type: String
           Description: EC2 reousrce instance type
           Value: t2.micro

        -  Name: &Param_KeyName KeyName
           Type: "AWS::EC2::KeyPair::KeyName"
           Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
           Value: demo-key

        -  Name: &Param_SSHLocation  SSHLocation
           Type: String
           Description: The IP address range that can be used to SSH to the EC2 instances
           Value: "0.0.0.0/0"

# Define anchors for data value
# Does not generate anything.
#

data:
        - SubNets:
             - VPC: &SubNetVPC 10.0.0.0/16
             - Public: &SubNetPublic 10.0.0.0/24
             - Private: &SubNetPrivate 10.0.1.0/24

mappings:
        - AmazonVpcNat: 
            Name: &MappingNatAim MappingNatAim

resources:


        - VPC:
                 Name: &MyVPC MyVPC
                 CidrBlock: *SubNetVPC
                 Tags:
                    - Key: Name
                      Value: "MyVPC"

        -  RouteTable: 
                 Name: &RouteTableNat RouteTableNat
                 Vpc: *MyVPC

        # -  RouteTable: 
        #          Name: &RouteTableMain RouteTableMain
        #          Vpc: *MyVPC


        - Subnet:
                 Name: &PublicSubnet PublicSubnet
                 DependsOn: *MyVPC
                 MapPublicIpOnLaunch: true
                 CidrBlock: *SubNetPublic
                 VpcId: *MyVPC
                 Tags:
                    - Key: Name
                      Value: *PublicSubnet

        - Subnet:
                 Name: &PrivateSubnet PrivateSubnet
                 DependsOn: *MyVPC
                 MapPublicIpOnLaunch: false
                 CidrBlock: *SubNetPrivate
                 VpcId: *MyVPC
                 Tags:
                    - Key: Name
                      Value: *PrivateSubnet
                 RoutetableAssociation: *RouteTableNat


        - InternetGateway: 
                 Name: &MyInternetGw MyInternetGw
                 Subnet: *PublicSubnet
                 Attachment:
                       AttachmentName: &AttachIgw MyInternetGwAttachment
                       Vpc: *MyVPC

        - SecurityGroup:
                 Name: &BackendSG BackendSecurityGroup
                 VpcId:
                   Ref: *MyVPC
                 SecurityGroupIngress:

                      # ssh
                    - Value: *SubNetPublic
                      Port: 22
                      
                      # ping
                    - Value: *SubNetVPC
                      FromPort: -1
                      ToPort: -1
                      IpProtocol: icmp


                 SecurityGroupEgress:
                    - Value: 0.0.0.0/0
                      Port: 80

                    - Value: 0.0.0.0/0
                      FromPort: -1
                      ToPort: -1
                      IpProtocol: icmp


        - SecurityGroup:
                 Name: &FrontSG FrontEndSecurityGroup
                 VpcId:
                   Ref: *MyVPC
                 SecurityGroupIngress:

                      # ssh
                    - Ref: *Param_SSHLocation
                      Port: 22

                      # Ping
                    - Value: 0.0.0.0/0
                      FromPort: -1
                      ToPort: -1
                      IpProtocol: icmp

                      # Http from private net
                    - Value: 0.0.0.0/0
                      Port: 80

                 SecurityGroupEgress:
                    - Value: *SubNetPrivate
                      Port: 22

                    - Value: 0.0.0.0/0
                      Port: 80

                    - Value: 0.0.0.0/0
                      Port: 443

                    - Value: 0.0.0.0/0
                      FromPort: -1
                      ToPort: -1
                      IpProtocol: icmp

        - SecurityGroup:
                 Name: &NatSG NatSecurityGroup
                 VpcId:
                   Ref: *MyVPC
                 SecurityGroupIngress:

                      # ssh
                    - Ref: *Param_SSHLocation
                      Port: 22

                      # Ping
                    - Value: 0.0.0.0/0
                      FromPort: -1
                      ToPort: -1
                      IpProtocol: icmp

                      # Http from private net
                    - Value: *SubNetPrivate
                      Port: 80

                 SecurityGroupEgress:
                    - Value: *SubNetPrivate
                      Port: 22

                    - Value: 0.0.0.0/0
                      Port: 80

                    - Value: 0.0.0.0/0
                      FromPort: -1
                      ToPort: -1
                      IpProtocol: icmp



        -  Instance: 
                 Name: &Instance3 myNat

                 InstanceTypeRef: *Param_InstanceTypeName

                 MapRegionToImageId: *MappingNatAim

                 KeyName: *Param_KeyName

                 # For the instance to perform NAT, the value must be
                 # "false". Notice String!!!
                 SourceDestCheck: "false"

                 # CreationPolicy: 
                 #     Timeout: PT8M

                 # Initialize: 
                 #   - InstallCFtools: true
                 # DependsOn: 
                 #  - *AttachIgw

                 SubnetId:
                       - Ref: *PublicSubnet

                 SecurityGroupIds: 
                       - Ref: *NatSG





        -  Instance: 
                 Name: &Instance2 myBack1

                 InstanceTypeRef: *Param_InstanceTypeName

                 KeyName: *Param_KeyName

                 # Fails because no internet connection to download 
                 # cfn-tools
                 # CreationPolicy: 
                 #     Timeout: PT8M

                 # Initialize: 
                 #   - InstallCFtools: true

                 SubnetId:
                       - Ref: *PrivateSubnet

                 SecurityGroupIds: 
                       - Ref: *BackendSG

        -  Instance: 
                 Name: &Instance1 myFront1

                 InstanceTypeRef: *Param_InstanceTypeName

                 KeyName: *Param_KeyName

                 DependsOn:
                   - *Instance2
                   - *Instance3


                 CreationPolicy: 
                     Timeout: PT8M

                 Initialize: 
                   - InstallCFtools: true

                 SubnetId:
                       - Ref: *PublicSubnet

                 SecurityGroupIds: 
                       - Ref: *FrontSG



        -  Route: 
                 Name: RouteToNat
                 Vpc: *MyVPC
                 # DependsOn: 
                 #  - *AttachIgw
                 RouteTableId: *RouteTableNat
                 InstanceId: *Instance3
                 DestinationCidrBlock: "0.0.0.0/0"

        # -  Route: 
        #          Name: RouteMain
        #          Vpc: *MyVPC
        #          RouteTableId: *RouteTableMain
        #          GatewayId: *MyInternetGw
        #          DestinationCidrBlock: "0.0.0.0/0"


outputs:

        -  Name: *Instance1
           Description: Ip of the newly created EC2 instance
           Attr: 
                 Ref: *Instance1
                 Name: PublicIp

        -  Name: *Instance3
           Description: Ip of the newly created EC2 instance
           Attr: 
                 Ref: *Instance3
                 Name: PublicIp


        # -  Name: *Instance2
        #    Description: Ip of the newly created EC2 instance
        #    Attr: 
        #          Ref: *Instance2
        #          Name: PublicIp

        -  Name: InstanceId1
           Description: Id of the newly created EC2 instance
           Ref: *Instance1

        -  Name: InstanceId2
           Description: Id of the newly created EC2 instance
           Ref: *Instance2

        -  Name: *MyInternetGw
           Description: Id of InternetGateway
           Ref: *MyInternetGw

