description: Example configuration for VPC


parameters:

        -  Name: &Param_InstanceTypeName InstanceType
           Type: String
           Description: EC2 reousrce instance type
           Value: t2.micro

        -  Name: &Param_KeyName KeyName
           Type: "AWS::EC2::KeyPair::KeyName"
           Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
           Value: demo-key

        -  Name: &Param_SSHLocation  SSHLocation
           Type: String
           Description: The IP address range that can be used to SSH to the EC2 instances
           Value: "0.0.0.0/0"

# Define anchors for data value
# Does not generate anything.
#

data:
        - SubNets:
             - VPC: &SubNetVPC 10.0.0.0/16
             - Public: &SubNetPublic 10.0.0.0/24
             - Private: &SubNetPrivate 10.0.1.0/24

resources:


        - VPC:
                 Name: &MyVPC MyVPC
                 CidrBlock: *SubNetVPC
                 Tags:
                    - Key: Name
                      Value: "MyVPC"

        - Subnet:
                 Name: &PublicSubnet PublicSubnet
                 DependsOn: *MyVPC
                 MapPublicIpOnLaunch: true
                 CidrBlock: *SubNetPublic
                 VpcId: *MyVPC
                 Tags:
                    - Key: Name
                      Value: *PublicSubnet

        - Subnet:
                 Name: &PrivateSubnet PrivateSubnet
                 DependsOn: *MyVPC
                 MapPublicIpOnLaunch: false
                 CidrBlock: *SubNetPrivate
                 VpcId: *MyVPC
                 Tags:
                    - Key: Name
                      Value: *PrivateSubnet


        - InternetGateway: 
                 Name: &MyInternetGw MyInternetGw
                 Vpc: *MyVPC
                 Subnet: *PublicSubnet
                 Tags:
                    - Key: Name
                      Value: *MyInternetGw


        - SecurityGroup:
                 Name: &DefaultSG MyDefaultSecurityGroup
                 VpcId:
                   Ref: *MyVPC
                 SecurityGroupIngress:

                      # ssh
                    - Ref: *Param_SSHLocation
                      Port: 22

                      # Ping
                    - Value: 0.0.0.0/0
                      FromPort: 8
                      ToPort: -1
                      IpProtocol: icmp


        -  Instance: 
                 Name: &Instance1 myFront1

                 InstanceTypeRef: *Param_InstanceTypeName

                 KeyName: *Param_KeyName

                 CreationPolicy: 
                     Timeout: PT8M

                 Initialize: 
                   - InstallCFtools: true

                 SubnetId:
                       - Ref: *PublicSubnet

                 SecurityGroupIds: 
                       - Ref: *DefaultSG

                 Tags:
                    - Key: Name
                      Value: *Instance1


        -  Instance: 
                 Name: &Instance2 myBack1

                 InstanceTypeRef: *Param_InstanceTypeName

                 KeyName: *Param_KeyName

                 # Fails because no internet connection to download 
                 # cfn-tools
                 # CreationPolicy: 
                 #     Timeout: PT8M

                 # Initialize: 
                 #   - InstallCFtools: true

                 SubnetId:
                       - Ref: *PrivateSubnet

                 SecurityGroupIds: 
                       - Ref: *DefaultSG

                 Tags:
                    - Key: Name
                      Value: *Instance2



outputs:

        -  Name: *Instance1
           Description: Ip of the newly created EC2 instance
           Attr: 
                 Ref: *Instance1
                 Name: PublicIp

        # -  Name: *Instance2
        #    Description: Ip of the newly created EC2 instance
        #    Attr: 
        #          Ref: *Instance2
        #          Name: PublicIp

        -  Name: InstanceId1
           Description: Ip of the newly created EC2 instance
           Ref: *Instance1

        -  Name: InstanceId2
           Description: Ip of the newly created EC2 instance
           Ref: *Instance2

        -  Name: *MyInternetGw
           Description: Id of InternetGateway
           Ref: *MyInternetGw

